apiVersion: v1
kind: ConfigMap
metadata:
  name: api-integration-config
data:
  APP_NAME: "API_INTEGRATION"
  APP_ENVIRONMENT: "DEVELOPMENT"
  APP_CLIENT: "DEMO"
  APP_VERSION: "1.0.0"

  DB_CONNECTION_POSTGRES: "POSTGRES"
  DB_CONNECTION_TYPE_POSTGRES: "POOL"
  DB_HOST_POSTGRES: "postgres"
  DB_PORT_POSTGRES: "5432"
  DB_NAME_POSTGRES: "api_integration_db"

  HTTP_ENVIRONMENT: "DEVELOPMENT"
  HTTP_URL: "0.0.0.0"
  HTTP_PORT: "3002"
  RATE_LIMITATING: "10-M"
  
  RABBITMQ_QUEUE_EXCHANGE: "app_events"
  
