apiVersion: v1
kind: Secret
metadata:
  name: async-secret
type: Opaque
data:
  DB_USER_POSTGRES: YXN5bmNfbWVzc2FnaW5n
  DB_PASS_POSTGRES: YXN5bmNfbWVzc2FnaW5n
  RABBITMQ_URL: YW1xcDovL2FkbWluOmFkbWluQHJhYmJpdG1xOjU2NzIv
