apiVersion: v1
kind: ConfigMap
metadata:
  name: async-config
data:
  APP_NAME: "ASYNC_MESSAGING"
  APP_ENVIRONMENT: "DEVELOPMENT"
  APP_CLIENT: "DEMO"
  APP_VERSION: "1.0.0"

  DB_CONNECTION_POSTGRES: "POSTGRES"
  DB_CONNECTION_TYPE_POSTGRES: "POOL"
  DB_HOST_POSTGRES: "postgres"
  DB_PORT_POSTGRES: "5432"
  DB_NAME_POSTGRES: "async_messaging_db"

  HTTP_ENVIRONMENT: "DEVELOPMENT"
  HTTP_URL: "0.0.0.0"
  HTTP_PORT: "3003"
  RATE_LIMITATING: "10-M"
