apiVersion: v1
kind: ConfigMap
metadata:
  name: security-config
data:
  APP_NAME: "AUTH_SECURITY"
  APP_ENVIRONMENT: "DEVELOPMENT"
  APP_CLIENT: "DEMO"
  APP_VERSION: "1.0.0"

  DB_CONNECTION_POSTGRES: "POSTGRES"
  DB_CONNECTION_TYPE_POSTGRES: "POOL"
  DB_HOST_POSTGRES: "postgres"
  DB_PORT_POSTGRES: "5432"
  DB_NAME_POSTGRES: "auth_security_db"

  HTTP_ENVIRONMENT: "DEVELOPMENT"
  HTTP_URL: "0.0.0.0"
  HTTP_PORT: "3004"
  REF_TOKEN_DURATION: "14400"
  ACCESS_TOKEN_DURATION: "2"
  RATE_LIMITATING: "10-M"
  
