apiVersion: v1
kind: Secret
metadata:
  name: security-secret
type: Opaque
data:
  DB_USER_POSTGRES: YXV0aF9zZWN1cml0eQ==
  DB_PASS_POSTGRES: YXV0aF9zZWN1cml0eQ==
  JWT_ACCESS_SEED: MTIzNTEyMzEyMzQxMg==
  JWT_REFRESH_SEED: MDI3ODEyMzAyMTIxMg==
  MAIL_ADDRESS: cG9ydGZvbGlvLmRlbW9zdHJhdGlvbkBnbWFpbC5jb20=
  MAIL_PASSWORD: cW96aCBwaXN0IHJ2cXggbGVnZw==
  RABBITMQ_URL: YW1xcDovL2FkbWluOmFkbWluQHJhYmJpdG1xOjU2NzIv

