apiVersion: v1
kind: Secret
metadata:
  name: api-integration-secret
type: Opaque
data:
  DB_USER_POSTGRES: YXBpX2ludGVncmF0aW9u
  DB_PASS_POSTGRES: YXBpX2ludGVncmF0aW9u
  DB_HOST_POSTGRES: cG9zdGdyZXM=
  DB_PORT_POSTGRES: NTQzMg==
  DB_NAME_POSTGRES: YXBpX2ludGVncmF0aW9uX2Ri
  RABBITMQ_URL: YW1xcDovL2FkbWluOmFkbWluQHJhYmJpdG1xOjU2NzIv
  HTTP_SECURITY_URL: aHR0cDovL2F1dGgtc2VjdXJpdHk6MzAwNC9zZWMvdmFsaWRhdGUtand0
