apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-reserves-config
data:
  APP_NAME: "AI_RESERVES"
  APP_ENVIRONMENT: "DEVELOPMENT"
  APP_CLIENT: "DEMO"
  APP_VERSION: "1.0.0"

  DB_CONNECTION_POSTGRES: "POSTGRES"
  DB_CONNECTION_TYPE_POSTGRES: "POOL"
  DB_HOST_POSTGRES: "postgres"
  DB_PORT_POSTGRES: "5432"
  DB_NAME_POSTGRES: "ai_reserves_db"

  HTTP_ENVIRONMENT: "DEVELOPMENT"
  HTTP_URL: "0.0.0.0"
  HTTP_PORT: "3006"
  RATE_LIMITATING: "10-M"
  
  RABBITMQ_QUEUE_EXCHANGE: "app_events"
  USER_CREATED_QUEUE: "user_created_q"
