apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-reserves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-reserves
  template:
    metadata:
      labels:
        app: ai-reserves
    spec:
      containers:
      - name: ai-reserves
        image: francoluciano/ai-reserves:latest
        ports:
        - containerPort: 3006

        envFrom:
        - configMapRef:
            name: ai-reserves-config
        - secretRef:
            name: ai-reserves-secret

        readinessProbe:
          httpGet:
            path: /api/healthcheck
            port: 3006
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /api/healthcheck
            port: 3006
          initialDelaySeconds: 10
          periodSeconds: 10
