apiVersion: v1
kind: Secret
metadata:
  name: ai-reserves-secret
type: Opaque
data:
  DB_USER_POSTGRES: YWlfcmVzZXJ2ZXM=         # ai_reserves
  DB_PASS_POSTGRES: YWlfcmVzZXJ2ZXM=         # ai_reserves
  DB_HOST_POSTGRES: cG9zdGdyZXM=             # postgres
  DB_PORT_POSTGRES: NTQzMg==                 # 5432
  DB_NAME_POSTGRES: YWlfcmVzZXJ2ZXNfZGI=     # ai_reserves_db

  HTTP_SECURITY_URL: aHR0cDovL2F1dGgtc2VjdXJpdHk6MzAwNC9zZWMvdmFsaWRhdGUtand0
  RABBITMQ_URL: YW1xcDovL2FkbWluOmFkbWluQHJhYmJpdG1xOjU2NzIv
